### ISSUE TITLE
local check_res = event_mgr:notify_listener("on_safe_text", user_id, name)

### ISSUE THREAD

**Issue by lonag** [xiyoo0812/quanta#30]
on_safe_text,全局搜不到了？
还有on_platform_login等。

**Comment by xiyoo0812** [comment]
1、引擎的登陆只支持PLATFORM_PASSWORD，on_platform_login是业务层为了支持第三方登录的事件扩展，使用引擎时使用PLATFORM_PASSWORD登陆。
2、on_safe_text这个也是第三方屏蔽词库查询，引擎层的确应该加一个空实现才对

**Comment by xiyoo0812** [comment]
> 1、引擎的登陆只支持PLATFORM_PASSWORD，on_platform_login是业务层为了支持第三方登录的事件扩展，使用引擎时使用PLATFORM_PASSWORD登陆。 2、on_safe_text这个也是第三方屏蔽词库查询，引擎层的确应该加一个空实现才对

已经在最新代码补充了2的空实现
