### ISSUE TITLE
socket_header* header = (socket_header*)slice->peek(sizeof(socket_header));

### ISSUE THREAD

**Issue by lonag** [xiyoo0812/quanta#31]
这个是不是用bytebuff 好点，其它语言的客户端，也好写解析代码。
对了，有客户端比如c#的demo吗？

**Comment by xiyoo0812** [comment]
协议本身分为消息头和消息体，消息头长度按照socket_header定义，消息体由业务自己编码管理！
Unity参考代码（C#）：
发送：
public short Send(ushort msgId, byte[] msgdata)
      {
          int offset = 0;

          int msgLength = msgdata.Length;
          int packageLength = msgLength + SendHeaderLength;

          byte[] data = _networkSolution.CreateRawPacket(packageLength);

          ushort length = (ushort)packageLength;
          //byte flag_byte = 0;//决定header的解析，是一个bitmask
          byte flag_byte = 1;//如 flag_byte = 1 | 4 | 8;
          ushort session_id = getNextSessionID();
          byte crc = 0;// CalculateCRC(msgdata);
          byte msg_type = msgId2msgbyte(msgId); ;// 1--lobby    2--scene  3--chat    4--friend  5--team
          data.WriteUInt16(ref offset, length);    //socket_header.len write
          data.WriteByte(ref offset, flag_byte);//socket_header.flag
          data.WriteByte(ref offset, msg_type);//socket_header.type
          data.WriteUInt16(ref offset, msgId);//socket_header.cmd_id
          data.WriteUInt16(ref offset,session_id);//socket_header.session_id
          //先写回,整体计算全部包体的crc之后写回crc信息
          data.WriteByte(ref offset, crc);
          int rememberCRC_offset = offset - 1;
          //data.WriteByte(ref offset, crc);

          data.WriteBytes(ref offset, msgdata, msgLength);
          //整个data写完，计算整个data的crc
          byte fullcrc = CalculateCRC(data);
          //写回crc位置
          data.WriteByte(ref rememberCRC_offset, fullcrc);

          LastSendMsgId = (short)msgId;
          LastSendState = _networkSolution.Send(data);

          //return AckNO;
          return (short)session_id;
      }

接受：
private void OnPacketReceived(byte[] data, int offset, int length)
        {
            int wholepacklen = data.ReadInt16(ref offset);//socket_header.len
            byte flag_byte = data.ReadByte(ref offset);//socket_header.flag
            byte msg_type = data.ReadByte(ref offset);//socket_header.type
            short msgId = data.ReadInt16(ref offset); // socket_header.cmdid
            short sessionId = data.ReadInt16(ref offset);//socket_header.sessionid
            byte crc = data.ReadByte(ref offset);//socket_header.crc8
            var msgLength = length - ReceiveHeaderLength; // Exclude header length
            var msgData = data.ReadBytes(ref offset, msgLength);
            MainThreadSynchronizer.Dispatch(() => DispatchMsg(msgId,sessionId, msgData));
        }
